# Site settings
title: ANTH&109
email: tbatey@my.lowercolumbia.edu
description: > # this means to ignore newlines until "baseurl:"
  A repository for American Cultural Diversity (ANTH&109) at Lower Columbia College
baseurl: "/Anth109" # the subpath of your site, e.g. /blog/
url: "http://tbatey.org" # the base hostname & protocol for your site
twitter_username: DocBatey
github_username:  bateyt
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
